name: transfer_news
description: Transfer and Indian football news

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  eva_icons_flutter: ^2.0.1

  #HTTP
  http: ^0.12.2

  #NavBar
  persistent_bottom_nav_bar: ^2.1.0
  line_awesome_icons: ^1.0.4+2
  flutter_vector_icons: ^0.2.1

  #Text Share
  google_fonts: ^1.1.0
  share: ^0.6.5+2
  google_sign_in: ^4.5.5

  #Important Dependencies
  image_picker: ^0.6.7+12
  uuid: ^2.2.2
  timeago: ^2.0.28
  video_player: ^1.0.0
  image_cropper: ^1.3.1
  flutter_launcher_icons: ^0.8.1
  percent_indicator: "^2.1.7+2"
  swipe_to: ^0.0.1+8

  #Web-dependencies
  flutter_webview_plugin: ^0.3.11
  flutter_html:
  cached_video_player: ^1.0.3
  html_editor: ^1.0.1
  dio: ^3.0.10

  #Permissions
  permission_handler: ^5.0.1+1

  #Animation
  morpheus: ^1.2.2+1
  flutter_staggered_animations: ^0.1.2
  delayed_display: ^1.0.3
  avatar_glow: ^1.2.0
  marquee: ^1.6.1

  #Local Database
  path_provider: ^1.6.24
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  #Database
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  community_material_icon: ^5.4.55

  #UI Dependencies
  flutter_linkify: ^4.0.2
  timeline_tile: ^1.0.0
  fluttertoast: ^7.1.1
  story_view: ^0.12.5
  story_designer: ^0.0.8+1
  flutter_unicons: ^0.0.3
  url_launcher: ^5.7.2
  jiffy: ^3.0.1
  shimmer: ^1.1.2
  tab_indicator_styler: ^1.0.0
  flutter_speed_dial: ^1.2.5

 #Cache Management
  flutter_cache_manager: ^2.0.0
  cached_network_image: ^2.3.3
  flutter_video_compress: ^0.3.7+8
  transparent_image: ^1.0.0
  image_gallery_saver: ^1.6.6

  #Youtube
  youtube_player_flutter: ^7.0.0+7
  video_compress: ^2.1.1

  #State Management
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5

 #Firebase Messaging
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
